package com.voku.textcleaner.core.rules

import com.voku.textcleaner.core.CleanupRuleSet

/**
 * GitHub PR/Issue cleanup rules.
 * Direct port of `src/core/rules/github.ts`.
 */
val GitHubRuleSet = CleanupRuleSet(
    name = "GitHub PR/Issue",
    prefixExactLines = listOf(
        "Skip to content",
        "Navigation Menu",
        "Repository navigation",
        "Code",
        "Issues",
        "Pull requests",
        "Agents",
        "Discussions",
        "Actions",
        "Projects",
        "Wiki",
        "Security and quality",
        "Notifications",
        "Fork",
        "Star",
        "Security",
        "Insights",
        "Settings",
        "Sign in",
        "Sign up",
    ),
    suffixExactLines = listOf(
        "Terms",
        "Privacy",
        "Docs",
        "Contact GitHub",
        "Contact",
        "Pricing",
        "API",
        "Training",
        "Blog",
        "About",
        "Status",
        "Security",
        "Manage cookies",
        "Do not share my personal information",
        "Community",
        "Footer navigation",
        "Footer",
        "1 participant",
        "You\u2019re receiving notifications because you were mentioned.",
        "Customize",
        "Notifications",
        "None yet",
        "Successfully merging this pull request may close these issues.",
        "Development",
        "No milestone",
        "Milestone",
        "Projects",
        "Labels",
        "No one\u2014",
        "Assignees",
        "Still in progress?",
        "+1 more reviewer",
        "Reviewers",
        "ProTip! Add comments to specific lines under Files changed.",
        "ProTip! Add .patch or .diff to the end of URLs for Git\u2019s plaintext views.",
        "Remember, contributions to this repository should follow our GitHub Community Guidelines.",
        "Add your comment here...",
        "Comment",
        "Add a comment",
        "You can also merge this with the command line.",
        "Merging can be performed automatically.",
        "No conflicts with base branch",
        "Contributor",
        "commented",
    ),
    prefixRegexes = listOf(
        Regex("^(?:- - - )?Skip to content$", RegexOption.IGNORE_CASE),
        Regex("^Search or jump to\\.\\.\\.$", RegexOption.IGNORE_CASE),
        Regex("^\\d+$", RegexOption.IGNORE_CASE),
        Regex("^\\(\\d+\\)$", RegexOption.IGNORE_CASE),
    ),
    suffixRegexes = listOf(
        Regex("^\u00A9 \\d{4} GitHub, Inc\\.$", RegexOption.IGNORE_CASE),
        Regex("^@.+$", RegexOption.IGNORE_CASE),
        Regex("^\\d+ more reviewer$", RegexOption.IGNORE_CASE),
    ),
    removeAnywhereExactLines = listOf(
        "Copy link",
        "Quote reply",
        "Reply",
        "Edit",
        "Delete",
        "Show options",
        "Hide options",
        "Add reaction",
        "React",
        "Rate limit exceeded",
        "\u231B How to resolve this issue?",
        "\uD83D\uDEA6 How do rate limits work?",
        "\u2139\uFE0F Review info",
        "\u2728 Finishing Touches",
        "Thanks for using CodeRabbit! It's free for OSS, and your support helps us grow. If you like it, consider giving us a shout-out.",
        "\u2764\uFE0F Share",
        "Comment @coderabbitai help to get the list of available commands and usage tips.",
        "This branch has not been deployed",
        "No deployments",
        "Merge info",
        "Some checks were not successful",
        "failing checks",
        "skipped checks",
        "neutral checks",
        "successful checks",
        "\u2022",
        "left a comment",
        "Code Review",
        "Walkthrough",
        "Changes",
        "Cohort / File(s)\tSummary",
        "Estimated code review effort",
        "Possibly related PRs",
        "\uD83D\uDCA1 Codex Review",
        "Here are some automated review suggestions for this pull request.",
        "\u2139\uFE0F About Codex in GitHub",
        "\uD83E\uDD16 Prompt for all review comments with AI agents",
        "Owner",
        "commented",
        "Contributor",
    ),
    removeAnywhereContains = emptyList(),
    removeAnywhereRegexes = listOf(
        Regex("^.* commented on .*$", RegexOption.IGNORE_CASE),
        Regex("^.* requested a review from .*$", RegexOption.IGNORE_CASE),
        Regex("^.* assigned .* to .*$", RegexOption.IGNORE_CASE),
        Regex("^.* added the .* label .*$", RegexOption.IGNORE_CASE),
        Regex("^.* removed the .* label .*$", RegexOption.IGNORE_CASE),
        Regex("^.* modified the milestones: .*$", RegexOption.IGNORE_CASE),
        Regex("^.* mentioned this issue .*$", RegexOption.IGNORE_CASE),
        Regex("^@.+ has exceeded the limit for the number of commits that can be reviewed per hour.*$", RegexOption.IGNORE_CASE),
        Regex("^Your organization is not enrolled in usage-based pricing.*$", RegexOption.IGNORE_CASE),
        Regex("^\\d+ failing, \\d+ neutral, \\d+ skipped, \\d+ successful checks$", RegexOption.IGNORE_CASE),
        Regex("^.*\\(pull_request\\).*$", RegexOption.IGNORE_CASE),
        Regex("^.*\\(pull_request_review\\).*$", RegexOption.IGNORE_CASE),
        Regex("^.*Successful in \\d+[sm].*$", RegexOption.IGNORE_CASE),
        Regex("^.*Failing after \\d+[sm].*$", RegexOption.IGNORE_CASE),
        Regex("^.*Skipped \\d+ (minutes|hours|days) ago.*$", RegexOption.IGNORE_CASE),
        Regex("^Code scanning results / CodeQL.*$", RegexOption.IGNORE_CASE),
        Regex("^CodeQL / Analyze.*$", RegexOption.IGNORE_CASE),
        Regex("^CodeRabbit \\S+ Review.*$", RegexOption.IGNORE_CASE),
        Regex("^Mend Security Check.*$", RegexOption.IGNORE_CASE),
        Regex("^Conversation\\d+ \\(\\d+\\)$", RegexOption.IGNORE_CASE),
        Regex("^Commits\\d+ \\(\\d+\\)$", RegexOption.IGNORE_CASE),
        Regex("^Checks\\d+ \\(\\d+\\)$", RegexOption.IGNORE_CASE),
        Regex("^Files changed\\d+ \\(\\d+\\)$", RegexOption.IGNORE_CASE),
        Regex("^Lines changed: \\d+ additions & \\d+ deletions$", RegexOption.IGNORE_CASE),
        Regex("^wants to merge \\d+ commits? into$", RegexOption.IGNORE_CASE),
        Regex("^.* wants to merge \\d+ commits? into .*$", RegexOption.IGNORE_CASE),
        Regex("^Reviewed commit: [a-f0-9]+$", RegexOption.IGNORE_CASE),
        Regex("^Comment on lines \\+\\d+ to \\+\\d+$", RegexOption.IGNORE_CASE),
        Regex("^\u26A0\uFE0F Outside diff range comments \\(\\d+\\)$", RegexOption.IGNORE_CASE),
        Regex("^DGS Integration Tests / .*$", RegexOption.IGNORE_CASE),
        Regex("^\\d+ (minute|hour|day|month|year)s? ago$", RegexOption.IGNORE_CASE),
        Regex("^.* reviewed \\d+ (minute|hour|day|month|year)s? ago$", RegexOption.IGNORE_CASE),
        Regex("^.*\\[bot]$", RegexOption.IGNORE_CASE),
        Regex("^.* bot$", RegexOption.IGNORE_CASE),
        Regex("^Useful\\? React with \uD83D\uDC4D / \uD83D\uDC4E\\.$", RegexOption.IGNORE_CASE),
        Regex("^Reply\\.\\.\\.$", RegexOption.IGNORE_CASE),
        Regex("^@.+\\s+Reply\\.\\.\\.$", RegexOption.IGNORE_CASE),
    ),
    preserveRegexes = listOf(
        Regex("^#+ "),                              // Headings
        Regex("^- "),                               // Bullets
        Regex("^\\* "),                             // Bullets
        Regex("^> "),                               // Blockquotes
        Regex("^```"),                              // Code blocks
        Regex("^[a-zA-Z0-9_.-]+\\.[a-zA-Z0-9]+$"), // Filenames
        Regex("^\\+ "),                             // Diff additions
        Regex("^- "),                               // Diff deletions
        Regex("^@@ .* @@"),                         // Diff headers
    ),
)
